### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by bogratt** [craigchristenson/magento-2checkout-api#11]
Hi - I'm having issues with the extension. Firstly it seems like the fields in Magento for 2checkout do not match what is in your instructions. For example #13 order status is not even a filed in my Magento. The paypal and credit card are 2 separate sections in the magento admin.

Then the INS does not seem to work. We get 404 errors for the path

http://www.xxxx.com/index.php/tco/notification/ins  (which we were told to use in the INS section in the 2CO admin).

I have uploaded all the files from Github 3 times thinking maybe there was a corrupt file.

Is there meant to be a tco folder? Paypal payments do not trigger sales emails to customer although the credit card ones do. In the Paypal orders there is a message  "Customer Not Notified Hash did not match, check secret word."
This makes no sense as there is no message like that for CC payments, and they both use the same settings, and the secret words do match.

Any help would be appreciated!

**Comment by craigchristenson** [comment]
Sorry for the issues. There were some incorrect instructions in the readme and some bugs in the module which made the INS flow none optimal. I have updated the readme and updated the module to update the order statuses appropriately.

New authorized orders are now initially set to processing instead of complete. Then based on your choice for "Invoice before fraud review" or "Invoice after fraud review" the order will be invoiced and set to complete when the appropriate INS message is recieved. The PayPal issue was caused by a bug where the secret word was not being pulled correctly which also has been fixed. The changes were tested against 1.8 and 1.9 community edition.

Please pull down master and let me know if you have any issues.

Thanks for reporting the bugs.

**Comment by bogratt** [comment]
Hi - thank you very much. I installed the new code and will test more orders, but the one order that came through, I got an email message about order being made from 2checkout, but in the 2checkout admin, the messages still get sent to the "failed" INS tab for messages. I'm using https://www.xxxxx.com/index.php/twocheckout/notification/ins as per the instructions. Is this wrong? Thanks!

**Comment by craigchristenson** [comment]
Yea that path is correct. Please feel free to hit me up directly at christensoncraig@gmail.com so that I can help you troubleshoot.
